version: "3.0"

services:
  ui:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: voyage_ui
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
  hh:
    image: 596511190950.dkr.ecr.us-west-2.amazonaws.com/voyage-core-contracts:latest
    container_name: voyage_core_contracts
    ports:
      - "8545:8545"

