version: "3.0"

services:
  ui:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: voyage_ui
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
