// noinspection HtmlUnknownTarget
import { Card, Title } from '@components/base';
import LineChart, { generateTimeSeries } from '@components/base/LineChart';
import { PoolProvider } from '@components/base/PoolProvider';
import PoolDetailCard from '@components/organisms/PoolDetailCard';
import TrancheDeposits from '@components/organisms/TrancheDeposits';
import UnbondingsCard from '@components/organisms/UnbondingsCard';
import { Grid } from '@mantine/core';
import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import styles from 'styles/Home.module.scss';

const ChartCards: React.FC = () => (
  <Grid>
    <Grid.Col span={4}>
      <Card style={{ height: 256, padding: '20px 24px' }}>
        <Title order={3}>TVL</Title>
        <LineChart
          data={generateTimeSeries(30, [0, 500_000_000], 10000, 0.01)}
        />
      </Card>
    </Grid.Col>
    <Grid.Col span={4}>
      <Card style={{ height: 256, padding: '20px 24px' }}>
        <Title order={3}>Utilization rate</Title>
        <LineChart
          name="Utilization Rate"
          data={generateTimeSeries(30, [0, 1], 0.05, 0.01)}
        />
      </Card>
    </Grid.Col>
    <Grid.Col span={4}>
      <Card style={{ height: 256, padding: '20px 24px' }}>
        <Title order={3}>Average Deposit APY</Title>
        <LineChart
          name="APY"
          data={generateTimeSeries(30, [0, 0.3], 0.05, 0.01)}
        />
      </Card>
    </Grid.Col>
  </Grid>
);

const PoolDetailPage: NextPage<{ symbol: string }> = ({ symbol }) => {
  return (
    <PoolProvider symbol={symbol}>
      <div>
        <Head>
          <title>Voyage Lend</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Grid align="stretch">
            <Grid.Col md={12} lg={3}>
              <PoolDetailCard />
            </Grid.Col>
            <Grid.Col md={12} lg={9}>
              <ChartCards />
              <Grid mt={13}>
                <Grid.Col md={12} lg={8}>
                  <TrancheDeposits />
                </Grid.Col>
                <Grid.Col md={12} lg={4}>
                  <UnbondingsCard />
                </Grid.Col>
              </Grid>
            </Grid.Col>
          </Grid>
        </main>
      </div>
    </PoolProvider>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  return {
    props: {
      symbol: params?.symbol,
    },
  };
};

export default PoolDetailPage;
