// noinspection HtmlUnknownTarget

import type { NextPage } from 'next';
import Head from 'next/head';
import { Grid, Group } from '@mantine/core';
import styles from 'styles/Home.module.scss';
import { Title, Card } from '@components/base';
import { GetServerSideProps } from 'next';
import PoolDetailCard from '@components/organisms/PoolDetailCard';
import TrancheCard from '@components/organisms/TrancheCard';
import { useState } from 'react';

const ChartCards: React.FC = () => (
  <Grid>
    <Grid.Col span={4}>
      <Card style={{ height: 256, padding: '20px 24px' }}>
        <Title order={3}>TVL</Title>
      </Card>
    </Grid.Col>
    <Grid.Col span={4}>
      <Card style={{ height: 256, padding: '20px 24px' }}>
        <Title order={3}>Utilization rate</Title>
      </Card>
    </Grid.Col>
    <Grid.Col span={4}>
      <Card style={{ height: 256, padding: '20px 24px' }}>
        <Title order={3}>Average Deposit APY</Title>
      </Card>
    </Grid.Col>
  </Grid>
);

const PoolDetail: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Voyage Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid>
          <Grid.Col span={3}>
            <PoolDetailCard />
          </Grid.Col>
          <Grid.Col span={9}>
            <Group direction="column" style={{ height: '100%' }} grow>
              <ChartCards />
              <Card>
                <Grid>
                  <Grid.Col span={6}>
                    <TrancheCard
                      type="Senior"
                      total={0}
                      totalUSD={0}
                      withdrawable={0}
                      withdrawableUSD={0}
                    />
                  </Grid.Col>
                  <Grid.Col span={6}>
                    <TrancheCard
                      type="Junior"
                      total={10000}
                      totalUSD={10000}
                      withdrawable={10000}
                      withdrawableUSD={10000}
                    />
                  </Grid.Col>
                </Grid>
              </Card>
            </Group>
          </Grid.Col>
        </Grid>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  return {
    props: {
      id: params?.id,
    },
  };
};

export default PoolDetail;
