// noinspection HtmlUnknownTarget

import type { NextPage } from 'next';
import Head from 'next/head';
import { Card, Grid, Group, useMantineTheme } from '@mantine/core';
import styles from 'styles/Home.module.scss';
import Image from 'next/image';
import PoolsTable from '@components/organisms/PoolsTable';
import { Text, Title } from '@components/base';
import { GetServerSideProps } from 'next';

const Cards: React.FC = () => (
  <Grid>
    <Grid.Col span={4}>
      <Card style={{ height: 256, padding: '20px 24px' }}>
        <Title order={3}>TVL</Title>
      </Card>
    </Grid.Col>
    <Grid.Col span={4}>
      <Card style={{ height: 256, padding: '20px 24px' }}>
        <Title order={3}>Utilization rate</Title>
      </Card>
    </Grid.Col>
    <Grid.Col span={4}>
      <Card style={{ height: 256, padding: '20px 24px' }}>
        <Title order={3}>Average Deposit APY</Title>
      </Card>
    </Grid.Col>
  </Grid>
);

const PoolDetail: NextPage = () => {
  const { other, colors } = useMantineTheme();

  return (
    <div>
      <Head>
        <title>Voyage Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid>
          <Grid.Col span={3}>
            <Card style={{ height: 776 }}>
              <Title>Crabada</Title>
              <Image
                src="/crabada-cover.png"
                alt="crabada"
                width={130}
                height={39}
              />
              <Text>
                A Fully Decentralised. Play-and-Earn Idle Game. Rediscover the
                prosperous ancient Crabada Kingdom once ruled by Crustaco, King
                of the Crabada.
              </Text>
            </Card>
          </Grid.Col>
          <Grid.Col span={9}>
            <Group direction="column" style={{ height: '100%' }} grow>
              <Cards />
              <Card>
                <Title>Deposit</Title>
              </Card>
            </Group>
          </Grid.Col>
        </Grid>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  return {
    props: {
      id: params?.id,
    },
  };
};

export default PoolDetail;
