// noinspection HtmlUnknownTarget

import type { NextPage } from 'next';
import Head from 'next/head';
import { useMantineTheme } from '@mantine/core';
import styles from 'styles/Home.module.css';
const Home: NextPage = () => {
  const { other, colors } = useMantineTheme();

  return (
    <div className={styles.container}>
      <Head>
        <title>Voyage Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
};

export default Home;
