name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64
      - name: Install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set envs
        run: |
          export SHORT_SHA=${GITHUB_SHA::7}
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
          export REF_NAME="$(echo ${GITHUB_REF_NAME} | sed 's/[^a-zA-Z0-9]/-/g')"
          echo "REF_NAME=${REF_NAME}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${REF_NAME//\//_}-${SHORT_SHA}-${{ github.run_number }}" >> $GITHUB_ENV
          echo IMAGE_TAG="${REF_NAME//\//_}-${SHORT_SHA}-${{ github.run_number }}"
      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: voyage-web-ui
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker buildx build --push \
            --cache-from=type=gha --cache-to=type=gha \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:"$IMAGE_TAG" \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$REF_NAME \
            --platform linux/amd64 \
            -f ./docker/Dockerfile .
          if [ "$GITHUB_REF_TYPE" == "tag" ]; then
            docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          fi
