name: Build
on: push
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: actions/setup-node@v3
        with:
          node-version: 17 
      - name: Install
        run: 'yarn install'
      - name: Build
        run: 'yarn build'
