name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - name: Install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: voyage-web-ui
          IMAGE_TAG: ${{ steps.short-sha.outputs.sha }}
        run: |
          docker buildx build --push \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -f ./docker/Dockerfile .
