name: Build
on: push
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install
        run: 'yarn install'
      - name: Build
        run: 'yarn build'
